config/routes.rb
Rails.application.routes.draw do


  resources :years, except: [:show]
  resources :instruments, except: [:show] do
    get 'ajax', to: "instruments#ajax"
    get 'ajaxd', to: "instruments#ajaxd"
  end
  resources :tarifs, except: [:show]
  resources :disciplines, except: [:show]

  resources :students do
    resources :cours
  end
  # resources :crenaus
  resources :adherent do
    resources :adhesions, only: [:new, :update]
    resources :students
    get 'query', to: 'students#query'
    get 'yes', to: 'students#yes'
    get 'querytwo', to: 'students#querytwo'
    get 'profile', to: "adherent#profile"
    resources :crenaus do
      get 'ajax', to: "crenaus#ajax"
    end
  end
  resources :users, only: [] do
    resources :crenaus, only: [:create, :show, :update, :destroy]
  end
devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do
    authenticated :user do
      root 'adherent#root', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
root 'pages#home'

get 'profs', to: 'adherent#profs'
get 'bureau', to: 'adherent#bureau'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :cours

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :year, presence: true

  def fullname
    self.first_name.capitalize + " " + self.last_name.capitalize
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :set_adherent, only: [:query, :querytwo, :yes, :new]

  def index
    if params[:query].present?
      sql_query = "first_name ILIKE :query OR last_name ILIKE :query"
      @students = Student.where(sql_query, query: "%#{params[:query]}%").order('first_name')
    else
      @students = Student.order('first_name')
    end
  end

  def show
    @adherent = @student.user
  end

  def query
  end

  def querytwo
  end

  def yes
    @hidden = "hidden"
    @student = Student.new({ user: @adherent })
  end

  def new
    @hidden = ""
    @student = Student.new({ user: @adherent })
  end

  def edit
    @adherent = @student.user
  end

  def create
    @student = Student.new(student_params)
      if @student.save
        redirect_to adherent_querytwo_path(@student.user), notice: 'Elève créé.'
      else
        render :new
      end
  end

  def update
    if @student.update(student_params)
      redirect_to @student, notice: 'Elève updaté.'
    else
      format.html { render :edit }
    end
  end

  def destroy
    user=@student.user
    @student.destroy
    redirect_to adherent_path(user), notice: 'Elève effacé.'
  end

  private
    def set_adherent
      @adherent = User.find(params["adherent_id"])
    end

    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:first_name, :last_name, :year, :user_id)
    end
end

app/views/students/_form.html.erb
  <%= @f.error_notification %>

  <div class="form-inputs">
    <div class="<%= @hidden %>">

      <% @student.first_name != nil ? sname = @student.first_name : sname =  @student.user.first_name %>
        <%= @f.input :first_name, label: 'Nom', :input_html => { :value => sname }, required: true  %>
      <% @student.last_name != nil ? slname = @student.last_name : slname =  @student.user.last_name %>
        <%= @f.input :last_name, label: 'Prénom', :input_html => { :value => slname }, required: true %>
    </div>
    <%= @f.input :year, label: 'Année de naissance', required: true %>
    <%= @f.association :user, :as => :hidden %>
  </div>

  <div class="form-actions">
    <%= @f.submit 'Sauvegarder', class: "btn btn-primary" %>
  </div>

app/views/students/edit.html.erb
<div class="myflex content-title">
  <p><%= render 'shared/logo' %> / Modifier un élève</p>
  <%= render 'shared/logout' %>
</div>
<div class="row back rowshadow">
  <div class="content col s12">
    <div class="content-form">
      <%= simple_form_for @student, :url => student_path(@student), :method => :put do |f| %>
        <% @f=f %>
        <%= render 'form', student: @student %>
      <% end %>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<div class="myflex content-title">
  <p><%= render 'shared/logo' %> / Liste d'élèves TOUTES SAISONS</p>
      <%= form_tag adherent_students_path(current_user), method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Rechercher un élève"
        %>
      <% end %>
  <%= render 'shared/logout' %>
</div>

<div class="row back rowshadow">
  <div class="content col s12">

    <div class="content-table">
      <%= render 'shared/studentslist' %>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<div class="myflex content-title">
  <p><%= render 'shared/logo' %> / Ajouter un élève</p>
  <%= render 'shared/logout' %>
</div>

<div class="row back rowshadow">
  <div class="content col s12">
    <div class="content-form">
      <%= simple_form_for @student, :url => adherent_students_path, :method => :post do |f| %>
        <% @f=f %>
        <%= render 'form', student: @student %>
      <% end %>
    </div>
  </div>
</div>

app/views/students/query.html.erb
<div class="title">
  <h4></h4>
  <h4>Etes vous l'élève ?</h4>
  <h4></h4>
</div>
<div class="mycard center">
  <%= link_to "Oui", adherent_yes_path(@adherent), class: "btn btn-success" %>
  <%= link_to "Non", new_adherent_student_path(@adherent), class: "btn btn-danger"  %>
  <%= link_to "Non et je n'en ai pas", adherent_path(@adherent), class: "btn btn-danger"  %>
</div>

app/views/students/querytwo.html.erb
<div class="title">
  <h4></h4>
  <h4>Ajouter un autre élève ?</h4>
  <h4></h4>
</div><div class="mycard center">
  <%= link_to "Oui", new_adherent_student_path(@adherent), class: "btn btn-success" %>
  <%= link_to "Non", adherent_path(@adherent), class: "btn btn-danger"  %>
</div>

app/views/students/show.html.erb
    <div class="myflex content-title">
      <p><%= render 'shared/logo' %> /
        <%= @student.fullname %></p>
      <%= render 'shared/logout' %>
    </div>
    <div class="content-bandeau myflex">
      <div>Elève</div>
      <%= @student.fullname %>
      <%= @student.year %>
      <%= link_to fa_icon('edit'), edit_student_path( @student), title: "Modifier" %>
    </div>
    <div class="content-table">
      <div class="row">
        <div class="col s12 m6">
          <%= render 'shared/courlist' %>
        </div>
        <div class="col s12 m6">
          <div class="conten-form">
            Comentaires :
          </div>
        </div>
      </div>
    </div>

app/views/students/yes.html.erb
<div class="title">
  <h4></h4>
  <h3>Y'a plus qu'a donner votre année de naissance!</h3>
  <h4></h4>
</div><div class="mycard center">
  <%= simple_form_for @student, :url => adherent_students_path, :method => :post do |f| %>
    <% @f=f %>
    <%= render 'form', student: @student %>
  <% end %>
</div>