config/routes.rb
Rails.application.routes.draw do


  resources :years, except: [:show]
  resources :instruments, except: [:show] do
    get 'ajax', to: "instruments#ajax"
    get 'ajaxd', to: "instruments#ajaxd"
  end
  resources :tarifs, except: [:show]
  resources :disciplines, except: [:show]

  resources :students do
    resources :cours
  end
  # resources :crenaus
  resources :adherent do
    resources :adhesions, only: [:new, :update]
    resources :students
    get 'query', to: 'students#query'
    get 'yes', to: 'students#yes'
    get 'querytwo', to: 'students#querytwo'
    get 'profile', to: "adherent#profile"
    resources :crenaus do
      get 'ajax', to: "crenaus#ajax"
    end
  end
  resources :users, only: [] do
    resources :crenaus, only: [:create, :show, :update, :destroy]
  end
devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do
    authenticated :user do
      root 'adherent#root', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
root 'pages#home'

get 'profs', to: 'adherent#profs'
get 'bureau', to: 'adherent#bureau'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/__creneaux.html.erb
<div class="myflex content-title">
  <p><%= link_to fa_icon('home'), adherent_path(@adherent) %>
<%= render 'shared/home' if ["Bureau", "Admin"].include?(@adherent.function.name) %>
   / Créneaux</p>
  <h4><%= link_to fa_icon('plus-circle'), "#{new_crenau_path}?prof=#{@adherent.id}", title: "Ajouter un créneau" if @auth %></h4>
</div>
<div class="row">

</div>

<%= render 'shared/tablecrenau' %>
<hr>
<div class="center"><u>Les créneaux ponctuels</u></div>
  <div class="content-table">
<%= render 'shared/oneshootcrenau' %>
</div>

app/views/shared/__tablecrenau.html.erb
    <div class="content-table">
      <div class="hcont">
        <table id= "crenautable" class="table-crenau">
          <tr>
              <td></td>
              <td></td>
            <% (8..21).each do |i| %>
              <td class="hrefer"><div class="hlabel"><%= i %>H</div></td>
              <td class=""></td>
              <td class=""></td>
              <td class="minfin"><div class="hlabelfin"><%= "22H" if i== 21 %></div></td>
            <% end %>
          </tr>
          <% (0..6).each do |j|
            jour = @jours[j] %>
            <tr>
              <td rowspan="2" class ="tjour"><%= @jours[j] %></td>
              <td class="rec">P</td>
              <% (8..21).each do |i| %>
                <td id='<%= "t#{j}_P_#{i}_0" %>' class="heureh"></td>
                <td id='<%= "t#{j}_P_#{i}_15" %>' class="minh"></td>
                <td id='<%= "t#{j}_P_#{i}_30" %>' class="minh"></td>
                <td id='<%= "t#{j}_P_#{i}_45" %>' class="minh <%= "cfin" if i== 21 %>"></td>
              <% end %>
            </tr>
            <tr>
              <td class="rec">I</td>
              <% (8..21).each do |i| %>
                <td id='<%= "t#{j}_I_#{i}_0" %>' class="heure"></td>
                <td id='<%= "t#{j}_I_#{i}_15" %>' class="min"></td>
                <td id='<%= "t#{j}_I_#{i}_30" %>' class="min"></td>
                <td id='<%= "t#{j}_I_#{i}_45" %>' class="min <%= "cfin" if i== 21 %>"></td>
              <% end %>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
<script type="text/javascript">
  // Mon code Javascript
  var vartop2 = document.body.querySelector("#t0_P_8_0").offsetLeft;
  var vartop3 = document.body.querySelector("#t0_P_21_45").offsetLeft;
  var width = ((vartop3-vartop2)/((14*4)-1)/15);

  <% @crenaus.each do |crenau|
    ms = (crenau.start.strftime("%M").to_i / 15).round * 15
    mhs = crenau.start.strftime("%H").to_i
    ids = "t#{crenau.jour}_P_" + mhs.to_s + "_"+ ms.to_s
    soff = crenau.start.strftime("%M").to_i - ms

    mstop = (crenau.end.strftime("%M").to_i / 15).round * 15
    mhstop = crenau.end.strftime("%H").to_i
    idstop = "t#{crenau.jour}_P_" + mhstop.to_s + "_"+ mstop.to_s
    stopoff = crenau.end.strftime("%M").to_i - mstop %>

    var height = document.body.querySelector("#t0_P_8_0").getBoundingClientRect().height;
    var x1 = document.body.querySelector("#<%= ids %>").offsetLeft;
    var x2 = document.body.querySelector("#<%= idstop %>").offsetLeft;
    var lenghtx = x2 - x1
    var offtop = -1

    <% case crenau.recurence %>
        <% when 0 %>
          height *= 2;
        <% when 1 %>
        <% when 2 %>
          offtop = height-1;
    <% end %>

    var min_start = Math.round(<%= soff %> * width)-1;
    var duree = lenghtx + ((<%= stopoff %> - <%= soff %>) * width)+1;
    var inst = "<%= crenau.instrument.name %>";
    var div='<a href="/crenaus/<%= crenau.id %>/edit"><div class="divcrenau myflex2 myalign" style="z-index:10; top: '+offtop+'px;left:'+min_start+'px;height:' + (height+1) + 'px;width:' + duree + 'px;">'+inst+'</div></a>'
    <% if crenau.recurence != 3 %>
      document.body.querySelector("#<%= ids %>").insertAdjacentHTML( 'afterbegin',  div);
    <% end %>
  <% end %>
  window.onresize = function(event) {location.reload();}
</script>

app/views/shared/_courlist.html.erb
  <table class="striped responsive-table">
    <thead>
      <tr>
        <th>Cours</th>
        <th>Instrument</th>
        <th>Année</th>
        <th></th>
        <th><%= link_to new_student_cour_path(@student) do  %>
    <i class="fa fa-plus-circle" aria-hidden="true" title="S'inscrire à un cours"></i>
    <% end %></th>
      </tr>
    </thead>
    <tbody>
      <% @student.cours.each do |cour| %>
        <% if @saison == cour.year %>
          <tr class="pointer" onclick="location.href='<%= edit_student_cour_path(@student, cour) %>'">
            <td><%= cour.discipline.name %></td>
            <td><%= cour.instrument.name %></td>
            <td><%= cour.year.name %></td>
            <td></td>
            <td>
              <%= link_to student_cour_path(@student, cour), class: "", method: :delete, data: { confirm: "Supprimer le cours?" } do %>
                <i class="fa fa-trash-o" aria-hidden="true"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

app/views/shared/_creneaux.html.erb
<div class="myflex content-title">
  <p><%= link_to fa_icon('home'), adherent_path(@adherent) %> / Créneaux</p>
  <h4><%= link_to fa_icon('plus-circle'), "#{new_crenau_path}?prof=#{@adherent.id}", title: "Ajouter un créneau" if @auth %></h4>
</div>
<div class="row">

</div>

<%= render 'shared/tablecrenau' %>
<hr>
<div class="center"><u>Les créneaux ponctuels</u></div>
  <div class="content-table">
<%= render 'shared/oneshootcrenau' %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <script type="text/javascript">
    var $toastContent = $('<span><%= notice %></span>').add($('<button class="btn-flat toast-action"><i class="fa fa-times" aria-hidden="true"></i></button>'));
    Materialize.toast($toastContent, 4000, 'blue rounded');
  </script>
<% end %>


<% if alert %>

  <script type="text/javascript">
    var $toastContent = $('<span><%= alert %></span>').add($('<button class="btn-flat toast-action"><i class="fa fa-times" aria-hidden="true"></i></button>'));
    Materialize.toast($toastContent, 4000, 'red rounded');
  </script>
<% end %>

app/views/shared/_home.html.erb
      <div class="content-title row">
        <div class="col s4">Membres :</div>
        <div class="col s4">Cours :</div>
        <div class="col s4">Paramètres :</div>
      </div>
      <div class="row">
        <div class="col s4">
          <ul>
            <li class="collection-item"><%= link_to " Bureau", bureau_path, class: "fa fa-users" %></li>
            <li class="collection-item"><%= link_to " Professeurs", profs_path, class: "fa fa-user-secret" %></li>
            <li class="collection-item"><%= link_to " Adhérents", adherent_index_path, class: "fa fa-user-circle" %></li>
            <li class="collection-item"><%= link_to " Elèves", students_path, class: "fa fa-graduation-cap" %></li>
          </ul>
        </div>
        <div class="col s4">
          <ul>
            <li class="collection-item"><%= link_to " Créneaux", crenaus_path, class: "fa fa-calendar" %></li>
            <li class="collection-item"><%= link_to " Inscriptions", "#", class: "fa fa-info" %></li>
          </ul>
        </div>
        <div class="col s4">
          <ul>
            <li class="collection-item"><%= link_to " Instruments", instruments_path, class: "fa fa-music" %></li>
            <li class="collection-item"><%= link_to " Formules", disciplines_path, class: "fa fa-server" %></li>
            <li class="collection-item"><%= link_to " Tarifs", tarifs_path, class: "fa fa-bitcoin" %></li>
            <li class="collection-item"><%= link_to " Saisons", years_path, class: "fa fa-black-tie" %></li>
          </ul>
        </div>
      </div>

app/views/shared/_logo.html.erb
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "logo.jpg", height: 30 %>
      <% end %>
      <%= link_to fa_icon('home'), adherent_path(@current_user) %> /
      <%= link_to @adherent.fullname, adherent_path(@adherent) %>

app/views/shared/_logout.html.erb
      <h4>
        <div class="myflex">
          <%= select_tag "saison", options_from_collection_for_select(Year.all.order('name').reverse, "id", "name", @saison.id),class: "saison", :onChange=>"javascript: window.location.href = `?saison=${this.value}`;" %>

          <ul id="dropdown1" class="dropdown-content dropdown">
            <li>
              <%= link_to adherent_profile_path(@adherent) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
          </ul>
          <a class="dropdown-button" href="#!" data-activates="dropdown1"><%= image_tag "avatar.jpg", class: "avatar " %></a>

        </div>
      </h4>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.jpg", height: 50 %>
  <% end %>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      Saison
      <%= select_tag "saison", options_from_collection_for_select(Year.all.order('name').reverse, "id", "name", @saison.id), :onChange=>"javascript: window.location.href = `?saison=${this.value}`;" %>
      <!-- Links when logged in -->
      <ul id="dropdown2" class="dropdown-content dropdown">
        <li><%= link_to " Bureau", bureau_path, class: "fa fa-users" %></li>
        <li><%= link_to " Professeurs", profs_path, class: "fa fa-user-secret" %></li>
        <li><%= link_to " Adhérents", adherent_index_path, class: "fa fa-user-circle" %></li>
        <li><%= link_to " Elèves", students_path, class: "fa fa-graduation-cap" %></li>
      </ul>
      <a class="dropdown-button waves-effect waves-light btn" href="#!" data-activates="dropdown2">Membres</a>

      <ul id="dropdown3" class="dropdown-content dropdown">
        <li><%= link_to " Instruments", instruments_path, class: "fa fa-music" %></li>
        <li><%= link_to " Formules", disciplines_path, class: "fa fa-server" %></li>
        <li><%= link_to " Tarifs", tarifs_path, class: "fa fa-bitcoin" %></li>
        <li class="divider"></li>
        <li><%= link_to " Saisons", years_path, class: "fa fa-black-tie" %></li>
      </ul>
      <a class="dropdown-button waves-effect waves-light btn" href="#!" data-activates="dropdown3">Paramètres</a>

      <ul id="dropdown4" class="dropdown-content dropdown">
        <li><%= link_to " Créneaux", crenaus_path, class: "fa fa-calendar" %></li>
        <li><%= link_to " Inscriptions", "#", class: "fa fa-info" %></li>
      </ul>
      <a class="dropdown-button waves-effect waves-light btn" href="#!" data-activates="dropdown4">Cours</a>


      <%= link_to "Profile", adherent_path(current_user), class: "waves-effect waves-light btn" %>
      <!-- Dropdown Structure -->
      <ul id="dropdown1" class="dropdown-content dropdown">
        <li>
          <%= link_to adherent_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li class="divider"></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
      </ul>
      <a class="dropdown-button" href="#!" data-activates="dropdown1"><%= image_tag "avatar.jpg", class: "avatar " %></a>


    <% else %>
      <!-- Login link (when logged out) -->
      <h4>Musique en l'Isle - administration</h4>
    <% end %>
  </div>

</div>

app/views/shared/_oneshootcrenau.html.erb
        <table class="striped responsive-table">
          <thead>
            <tr>
              <th>Prof</th>
              <th>Jour</th>
              <th>Recurence</th>
              <th>Instrument</th>
              <th>Discipline</th>
              <th>DE</th>
              <th>A</th>
              <th colspan="1"></th>
            </tr>
          </thead>

          <tbody>
            <% @crenaus.each do |crenau|
              if crenau.recurence == 3 %>
                <tr class="<%= crenau.valide %> pointer" onclick="location.href='<%= edit_crenau_path(crenau) %>'">


                  <td><%= crenau.user.fullname %></td>

                  <td><%= @jours[crenau.jour] %></td>
                  <td><%= @recurences[crenau.recurence] %></td>
                  <td><%= crenau.instrument.name %></td>
                  <td><%= crenau.discipline.name %></td>
                  <td><%= crenau.start.strftime("%H:%M") %></td>
                  <td><%= crenau.end.strftime("%H:%M") %></td>
                  <td><%= link_to fa_icon("trash-o"), crenau_path(crenau), method: :delete, data: { confirm: 'Supprimer le créneau?' } %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>

app/views/shared/_studentlist.html.erb
  <table class="striped responsive-table">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Année</th>
        <th>Adhérent</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr class="pointer" onclick="location.href='<%= student_path(student) %>'">
          <td><%= student.first_name %></td>
          <td><%= student.last_name %></td>
          <td><%= student.year %></td>
          <td><%= student.user.first_name %> <%= student.user.last_name %></td>
          <td>
            <%= link_to student, class: "secondary-content", method: :delete, data: { confirm: "Supprimer l'élève?" } do %>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/shared/_studentslist.html.erb
  <table class="striped responsive-table">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr class="pointer" onclick="location.href='<%= student_path(student) %>'">
          <td><%= student.first_name %></td>
          <td><%= student.last_name %></td>
          <td>
            <%= link_to student, class: "", method: :delete, data: { confirm: "Supprimer l'élève?" } do %>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/shared/_tablecrenau.html.erb
    <div class="content-table">
      <div class="hcont">
        <table id= "crenautable" class="table-crenau">
          <tr>
              <td></td>
              <td></td>
            <% (8..21).each do |i| %>
              <td class="hrefer"><div class="hlabel"><%= i %>H</div></td>
              <td class=""></td>
              <td class=""></td>
              <td class="minfin"><div class="hlabelfin"><%= "22H" if i== 21 %></div></td>
            <% end %>
          </tr>
          <% (0..6).each do |j|
            jour = @jours[j] %>
            <tr>
              <td rowspan="2" class ="tjour"><%= @jours[j] %></td>
              <td class="rec">P</td>
              <% (8..21).each do |i| %>
                <td id='<%= "t#{j}_P_#{i}_0" %>' class="heureh"></td>
                <td id='<%= "t#{j}_P_#{i}_15" %>' class="minh"></td>
                <td id='<%= "t#{j}_P_#{i}_30" %>' class="minh"></td>
                <td id='<%= "t#{j}_P_#{i}_45" %>' class="minh <%= "cfin" if i== 21 %>"></td>
              <% end %>
            </tr>
            <tr>
              <td class="rec">I</td>
              <% (8..21).each do |i| %>
                <td id='<%= "t#{j}_I_#{i}_0" %>' class="heure"></td>
                <td id='<%= "t#{j}_I_#{i}_15" %>' class="min"></td>
                <td id='<%= "t#{j}_I_#{i}_30" %>' class="min"></td>
                <td id='<%= "t#{j}_I_#{i}_45" %>' class="min <%= "cfin" if i== 21 %>"></td>
              <% end %>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
<script type="text/javascript">
  // Mon code Javascript
  var vartop2 = document.body.querySelector("#t0_P_8_0").offsetLeft;
  var vartop3 = document.body.querySelector("#t0_P_21_45").offsetLeft;
  var width = ((vartop3-vartop2)/((14*4)-1)/15);

  <% @crenaus.each do |crenau|
    ms = (crenau.start.strftime("%M").to_i / 15).round * 15
    mhs = crenau.start.strftime("%H").to_i
    ids = "t#{crenau.jour}_P_" + mhs.to_s + "_"+ ms.to_s
    soff = crenau.start.strftime("%M").to_i - ms

    mstop = (crenau.end.strftime("%M").to_i / 15).round * 15
    mhstop = crenau.end.strftime("%H").to_i
    idstop = "t#{crenau.jour}_P_" + mhstop.to_s + "_"+ mstop.to_s
    stopoff = crenau.end.strftime("%M").to_i - mstop %>

    var height = document.body.querySelector("#t0_P_8_0").getBoundingClientRect().height;
    var x1 = document.body.querySelector("#<%= ids %>").offsetLeft;
    var x2 = document.body.querySelector("#<%= idstop %>").offsetLeft;
    var lenghtx = x2 - x1
    var offtop = -1

    <% case crenau.recurence %>
        <% when 0 %>
          height *= 2;
        <% when 1 %>
        <% when 2 %>
          offtop = height-1;
    <% end %>

    var min_start = Math.round(<%= soff %> * width)-1;
    var duree = lenghtx + ((<%= stopoff %> - <%= soff %>) * width)+1;
    var inst = "<%= crenau.instrument.name %>";
    var div='<a href="/crenaus/<%= crenau.id %>/edit"><div class="divcrenau myflex2 myalign" style="z-index:10; top: '+offtop+'px;left:'+min_start+'px;height:' + (height+1) + 'px;width:' + duree + 'px;">'+inst+'</div></a>'
    <% if crenau.recurence != 3 %>
      document.body.querySelector("#<%= ids %>").insertAdjacentHTML( 'afterbegin',  div);
    <% end %>
  <% end %>
  window.onresize = function(event) {location.reload();}
</script>

app/views/shared/rebut_studentlist.html.erb
  <table class="striped responsive-table">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th><%= link_to new_adherent_student_path(@adherent) do  %>
    <i class="fa fa-plus-circle" aria-hidden="true" title="Ajouter un élève"></i>
    <% end %></th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr class="pointer" onclick="location.href='<%= student_path(student) %>'">
          <td><%= student.first_name %></td>
          <td><%= student.last_name %></td>
          <td>
            <%= link_to student, class: "", method: :delete, data: { confirm: "Supprimer l'élève?" } do %>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>