config/routes.rb
Rails.application.routes.draw do


  resources :years, except: [:show]
  resources :instruments, except: [:show] do
    get 'ajax', to: "instruments#ajax"
    get 'ajaxd', to: "instruments#ajaxd"
  end
  resources :tarifs, except: [:show]
  resources :disciplines, except: [:show]

  resources :students do
    resources :cours
  end
  # resources :crenaus
  resources :adherent do
    resources :adhesions, only: [:new, :update]
    resources :students
    get 'query', to: 'students#query'
    get 'yes', to: 'students#yes'
    get 'querytwo', to: 'students#querytwo'
    get 'profile', to: "adherent#profile"
    resources :crenaus do
      get 'ajax', to: "crenaus#ajax"
    end
  end
  resources :users, only: [] do
    resources :crenaus, only: [:create, :show, :update, :destroy]
  end
devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do
    authenticated :user do
      root 'adherent#root', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
root 'pages#home'

get 'profs', to: 'adherent#profs'
get 'bureau', to: 'adherent#bureau'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/crenau.rb
class Crenau < ApplicationRecord
  belongs_to :user
  belongs_to :year
  belongs_to :discipline
  belongs_to :instrument

  validates :instrument, presence: true
  validates :discipline, presence: true
  validates :user, presence: true
  validates :year, presence: true

  validates :jour, presence: true
  validates :recurence, presence: true
  validates :start, presence: true
  validates :end, presence: true




end

app/controllers/crenaus_controller.rb
class CrenausController < ApplicationController
  before_action :set_crenau, only: [:show, :edit, :update, :destroy]
  before_action :set_adherent, only: [:new, :show, :edit, :index, :destroy]
  skip_before_action :authenticate_user!, only: [:ajax, :ajaxd]
  # GET /crenaus
  # GET /crenaus.json
  def index
    @colors = {}
    @instindex = {}
    color ="10FF0F"
    i = 0
    Instrument.where(valide:true).each do |instrument|
      color = (color.to_i(16) + 1600000).to_s(16)
      @colors[instrument.id] = color + "9F"
      @instindex[instrument.id] = i
      i += 1
    end


    if ["Bureau", "Secrétaire", "Trésorier", "Président", "Admin"].include?(@adherent.function.name)
      @crenaus = Crenau.where(year: @saison).order(:valide)
      render :all
    else
      @crenaus = Crenau.where(user: @adherent).rewhere(year: @saison).order(:valide)
    end
  end

    # GET /crenaus/1
  # GET /crenaus/1.json
  def show
    @usercollection = User.joins(:function).where("functions.name = 'Professeur'").order('first_name')
    @instruments = Instrument.where(valide: true)
    @disciplines = Discipline.joins(:instruments).where(instruments: {id: @crenau.instrument.id})
    @cour = Cour.new
    @crenaus = [@crenau]
      @cours = Cour.where(instrument: @crenau.instrument.id).rewhere(discipline: @crenau.discipline.id).rewhere(year: @saison).reverse
  end

  # GET /crenaus/new
  def new
    @crenau = Crenau.new
    if @adherent.function.name == "Professeur"
      @usercollection = [@adherent]
      @crenau.user = @adherent
    else
      @usercollection = User.joins(:function).where("functions.name = 'Professeur'").order('first_name')
      @crenau.user = User.joins(:function).where("functions.name = 'Professeur'").last
    end
    @crenau.start = "9:00"
    @crenau.end = "22:00"
    @instruments = Instrument.where(valide: true)
    @disciplines = []
  end

  # GET /crenaus/1/edit
  def edit
    @usercollection = User.joins(:function).where("functions.name = 'Professeur'").order('first_name')
    @instruments = Instrument.where(valide: true)
    @disciplines = Discipline.joins(:instruments).where(instruments: {id: @crenau.instrument.id})
    @cour = Cour.new
    @crenaus = [@crenau]
      @cours = Cour.where(instrument: @crenau.instrument.id).rewhere(discipline: @crenau.discipline.id).rewhere(year: @saison).reverse
end

  # POST /crenaus
  # POST /crenaus.json
  def create
    @adherent = User.find(params[:user_id])

    @crenau = Crenau.new(crenau_params)
    if @adherent.function.name == "Professeur"
      @usercollection = [@adherent]
      @crenau.user = @adherent
    else
      @usercollection = User.joins(:function).where("functions.name = 'Professeur'").order('first_name')
      @crenau.user = User.joins(:function).where("functions.name = 'Professeur'").last
    end
    @crenau.recurence = @recurences.find_index { |w| w == params["crenau"]["recurence"] }
    @crenau.jour = @jours.find_index { |w| w == params["crenau"]["jour"] }
    if @crenau.save
      redirect_to adherent_crenaus_path(@adherent), notice: 'Creneau crée.'
    else
      render :new
    end
  end

  # PATCH/PUT /crenaus/1
  # PATCH/PUT /crenaus/1.json
  def update
    @adherent = User.find(params[:user_id])
    params["crenau"]["recurence"] = @recurences.find_index { |w| w == params["crenau"]["recurence"] }
    params["crenau"]["jour"] = @jours.find_index { |w| w == params["crenau"]["jour"] }
    @crenau.valide = params["crenau"]["valide"] == "true"
    if @crenau.update(crenau_params)
      redirect_to adherent_crenau_path(@adherent,@crenau), notice: 'Creneau sauvegardé.'
    else
      render :edit
    end
  end

  # DELETE /crenaus/1
  # DELETE /crenaus/1.json
  def destroy
    @crenau.destroy
    redirect_to adherent_crenaus_path(@adherent), notice: 'Creneau effacé.'
  end

  def ajax
    @crenaus = [Crenau.find(params[:crenau_id])]
    @cour = Cour.new
    render "_ajax", :layout => false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crenau
      @crenau = Crenau.find(params[:id])
    end

    def set_adherent
      @adherent = User.find(params[:adherent_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crenau_params
      params.require(:crenau).permit(:valide, :user_id, :year_id, :valide, :discipline_id, :instrument_id, :jour, :recurence, :start, :end)
    end
end

app/views/crenaus/_ajax.html.erb
  <% if @cour.id
      value = @cour.dispo
      classe = ""
    else
      value = ""
      classe ="sticky"
    end
    tab = value.split(',')
  %>
<div class="row <%= classe %>">
  <div class="col s10">
    <input name="dispo" type="hidden" id="finput" value="<%= value %>" class="<%= tab.join(' ') %>">
        <% @crenaus.each do |crenau|
          ms = (crenau.start.strftime("%M").to_i / 15).round * 15
          mhs = crenau.start.strftime("%H").to_i
          ids = "t#{crenau.id}_P_" + mhs.to_s + "_"+ ms.to_s
          soff = crenau.start.strftime("%M").to_i - ms

          mstop = (crenau.end.strftime("%M").to_i / 15).round * 15
          crenau.end.strftime("%M").to_i == 0 ? toff =0 : toff=1
          mhstop = crenau.end.strftime("%H").to_i+toff
          idstop = "t#{crenau.id}_P_" + mhstop.to_s + "_"+ mstop.to_s
          stopoff = crenau.end.strftime("%M").to_i - mstop %>

      <table id= "crenautable" class="table-crenau">
        <% unless @cour.id %>
          <tr>
              <td class="hrefer">
                <div class="elabel">
                  <%= link_to "Modifier", edit_adherent_crenau_path(@adherent,crenau) %>
                </div>
              </td>
              <td></td>
            <% (mhs...mhstop).each do |i| %>
              <td id='<%= "t_P_#{i}_0" %>' class="hrefer"><div class="hlabel"><%= i %>H</div></td>
              <td id='<%= "t_P_#{i}_15" %>' class=""></td>
              <td id='<%= "t_P_#{i}_30" %>' class=""></td>
              <td id='<%= "t_P_#{i}_45" %>' class="minfin"><div class="hlabelfin"><%= "#{mhstop}H" if i== mhstop-1 %></div></td>
            <% end %>
          </tr>
        <% end %>
          <tr>
            <td rowspan="2" class ="tjour" style="width: 100px !important;"><%= @cour.id ? @cour.student.last_name : @jours[crenau.jour] %></td>
            <td class="rec">P</td>
            <% (mhs...mhstop).each do |i|
              @cstart = crenau.start.strftime("%H%M").to_i
              @cend = crenau.end.strftime("%H%M").to_i
              crec = crenau.recurence
              @cp =false
              @ci = false
              @cp=true if crec == 0 or crec == 1
              @ci=true if crec == 0 or crec == 2 %>

            <% @cstart<= i*100 and @cend > i*100+14 ? myclass="jaune" : myclass="" %>
            <% myclass="vert" if tab.include?("t_#{crenau.id}_P_#{i}_0") %>
              <td id='<%= "t_#{crenau.id}_P_#{i}_0" %>' class="heureh <%= myclass if @cp %>" onmousedown="set(this);" onmouseup="unset(this)" onmousemove="cset(this)"></td>
            <% @cstart<= i*100+15 and @cend > i*100+29  ? myclass="jaune" : myclass="" %>
            <% myclass="vert" if tab.include?("t_#{crenau.id}_P_#{i}_15") %>
              <td id='<%= "t_#{crenau.id}_P_#{i}_15" %>' class="minh <%= myclass if @cp %>" onmousedown="set(this);" onmouseup="unset(this)" onmousemove="cset(this)"></td>
            <% @cstart<= i*100+30 and @cend > i*100+44  ? myclass="jaune" : myclass="" %>
            <% myclass="vert" if tab.include?("t_#{crenau.id}_P_#{i}_30") %>
              <td id='<%= "t_#{crenau.id}_P_#{i}_30" %>' class="minh <%= myclass if @cp %>" onmousedown="set(this);" onmouseup="unset(this)" onmousemove="cset(this)"></td>
            <% @cstart<= i*100+45 and @cend > i*100+59  ? myclass="jaune" : myclass="" %>
            <% myclass="vert" if tab.include?("t_#{crenau.id}_P_#{i}_45") %>
              <td id='<%= "t_#{crenau.id}_P_#{i}_45" %>' class="minh <%= myclass if @cp %> <%= "cfin" if i== mhstop-1 %>" onmousedown="set(this);" onmouseup="unset(this)" onmousemove="cset(this)"></td>
            <% end %>
              <td id='<%= "t_#{crenau.id}_P_#{mhstop}_0" %>' style="visibility: hidden;" class="heureh"></td>
          </tr>
          <tr>
            <td class="rec">I</td>
            <% (mhs...mhstop).each do |i| %>

            <% @cstart<= i*100 and @cend > i*100+14 ? myclass="jaune" : myclass="" %>
            <% myclass="vert" if tab.include?("t_#{crenau.id}_I_#{i}_0") %>
              <td id='<%= "t_#{crenau.id}_I_#{i}_0" %>' class="heure <%= myclass if @ci %> " onmousedown="set(this);" onmouseup="unset(this)" onmousemove="cset(this)"></td>
            <% @cstart<= i*100+15 and @cend > i*100+29  ? myclass="jaune" : myclass="" %>
            <% myclass="vert" if tab.include?("t_#{crenau.id}_I_#{i}_15") %>
              <td id='<%= "t_#{crenau.id}_I_#{i}_15" %>' class="min <%= myclass if @ci %> " onmousedown="set(this);" onmouseup="unset(this)" onmousemove="cset(this)"></td>
            <% @cstart<= i*100+30 and @cend > i*100+44  ? myclass="jaune" : myclass="" %>
            <% myclass="vert" if tab.include?("t_#{crenau.id}_I_#{i}_30") %>
              <td id='<%= "t_#{crenau.id}_I_#{i}_30" %>' class="min <%= myclass if @ci %> " onmousedown="set(this);" onmouseup="unset(this)" onmousemove="cset(this)"></td>
            <% @cstart<= i*100+45 and @cend > i*100+59  ? myclass="jaune" : myclass="" %>
            <% myclass="vert" if tab.include?("t_#{crenau.id}_I_#{i}_45") %>
              <td id='<%= "t_#{crenau.id}_I_#{i}_45" %>' class="min <%= myclass if @ci %>  <%= "cfin" if i== mhstop-1 %>" onmousedown="set(this);" onmouseup="unset(this)" onmousemove="cset(this)"></td>
            <% end %>
              <td id='<%= "t_#{crenau.id}_I_#{mhstop}_0" %>' style="visibility: hidden;" class="heure"></td>
          </tr>

      </table>
      <div class="comments">
        <% autrecrenau = false
          if @cour.id
            @cour.dispo.split(",").each do |dispo|
              autrecrenau = true if dispo.split("_")[1].to_i != crenau.id
            end
          end
          if autrecrenau  %>
            <strong>Elève avec des dispo dans un autre crénau</strong><br/>
          <% end %>
        <%= @cour.comments %>

      </div>

        <% end %>
  </div>
</div>

app/views/crenaus/all.html.erb
<div class="myflex content-title">
  <p><%= render 'shared/logo' %> / Planning</p>

  <%= render 'shared/logout' %>
</div>


<div class="content-table">
  <div class="hcont">
    <table id= "crenautable" class="table-crenau">
      <tr>
          <td class="hrefer"><div class="plabel"><%= link_to fa_icon('plus-circle'), new_adherent_crenau_path(@adherent), title: "Ajouter un créneau" %></div></td>
          <td></td>
          <td></td>
        <% (8..21).each do |i| %>
          <td id='<%= "t0_P_#{i}_0" %>' class="htd hrefer"><div class="hlabel"><%= i %>H</div></td>
          <td id='<%= "t0_P_#{i}_15" %>' class="htd"></td>
          <td id='<%= "t0_P_#{i}_30" %>' class="htd"></td>
          <td id='<%= "t0_P_#{i}_45" %>' class="htd minfin"><div class="hlabelfin"><%= "22H" if i== 21 %></div></td>
        <% end %>
      </tr>
      <% (0..6).each do |j| %>

            <td rowspan="<%= @colors.count*2+1 %>" class ="tjour  pjour"><%= @jours[j] %></td>

        <% @colors.each do |key, color| %>
          <% @cinstrument = Instrument.find(key) %>
          <tr>
            <td rowspan="2" class ="tinst" style="background-color: #<%= color %>;"><%= @cinstrument.name %></td>
            <td class="rec" style="background-color: #<%= color %>;">P</td>
            <% (8..21).each do |i| %>
              <td id='<%= "t#{key}_#{j}_P_#{i}_0" %>' class="heureh"></td>
              <td id='<%= "t#{key}_#{j}_P_#{i}_15" %>' class="minh"></td>
              <td id='<%= "t#{key}_#{j}_P_#{i}_30" %>' class="minh"></td>
              <td id='<%= "t#{key}_#{j}_P_#{i}_45" %>' class="minh <%= "cfin" if i== 21 %>"></td>
            <% end %>
              <td id='<%= "t#{key}_#{j}_P_22_0" %>' style="visibility: hidden;" class="heureh"></td>
          </tr>
          <tr>
            <td class="rec" style="background-color: #<%= color %>;">I</td>
            <% (8..21).each do |i| %>
              <td id='<%= "t#{key}_#{j}_I_#{i}_0" %>' class="heure"></td>
              <td id='<%= "t#{key}_#{j}_I_#{i}_15" %>' class="min"></td>
              <td id='<%= "t#{key}_#{j}_I_#{i}_30" %>' class="min"></td>
              <td id='<%= "t#{key}_#{j}_I_#{i}_45" %>' class="min <%= "cfin" if i== 21 %>"></td>
            <% end %>
              <td id='<%= "t#{key}_#{j}_I_22_0" %>' style="visibility: hidden;" class="heure"></td>
          </tr>

        <% end %>



      <% end %>
    </table>
  </div>
</div>


<hr>
<div class="center"><u>Les créneaux ponctuels</u></div>
  <div class="content-table">
        <table class="striped responsive-table">
          <thead>
            <tr>
              <th>Prof</th>
              <th>Jour</th>
              <th>Recurence</th>
              <th>Instrument</th>
              <th>Discipline</th>
              <th>DE</th>
              <th>A</th>
              <th colspan="1"></th>
            </tr>
          </thead>

          <tbody>
            <% @crenaus.each do |crenau|
              if crenau.recurence == 3 %>
                <tr class="<%= crenau.valide %> pointer" onclick="location.href='<%= edit_adherent_crenau_path(@adherent,crenau) %>'">


                  <td><%= crenau.user.fullname %></td>

                  <td><%= @jours[crenau.jour] %></td>
                  <td><%= @recurences[crenau.recurence] %></td>
                  <td><%= crenau.instrument.name %></td>
                  <td><%= crenau.discipline.name %></td>
                  <td><%= crenau.start.strftime("%H:%M") %></td>
                  <td><%= crenau.end.strftime("%H:%M") %></td>
                  <td><%= link_to fa_icon("trash-o"), adherent_crenau_path(@adherent,crenau), method: :delete, data: { confirm: 'Supprimer le créneau?' } %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
</div>



<script type="text/javascript">
  // Mon code Javascript
  var vartop2 = document.body.querySelector("#t0_P_8_0").offsetLeft;
  var vartop3 = document.body.querySelector("#t0_P_21_45").offsetLeft;
  var width = ((vartop3-vartop2)/((14*4)-1)/15);

  <% @crenaus.each do |crenau|
    ms = (crenau.start.strftime("%M").to_i / 15).round * 15
    mhs = crenau.start.strftime("%H").to_i
    ids = "t#{crenau.instrument.id}_#{crenau.jour}_P_" + mhs.to_s + "_"+ ms.to_s
    soff = crenau.start.strftime("%M").to_i - ms

    mstop = (crenau.end.strftime("%M").to_i / 15).round * 15
    mhstop = crenau.end.strftime("%H").to_i
    idstop = "t#{crenau.instrument.id}_#{crenau.jour}_P_" + mhstop.to_s + "_"+ mstop.to_s
    stopoff = crenau.end.strftime("%M").to_i - mstop %>

    var height = document.body.querySelector("#<%= ids %>").getBoundingClientRect().height;
    var x1 = document.body.querySelector("#<%= ids %>").offsetLeft;
    var x2 = document.body.querySelector("#<%= idstop %>").offsetLeft;
    var lenghtx = x2 - x1
    var offtop = -1

    <% case crenau.recurence %>
        <% when 0 %>
          height *= 2;
        <% when 1 %>
        <% when 2 %>
          offtop = height-1;
    <% end %>

    var min_start = Math.round(<%= soff %> * width)-1;
    var duree = lenghtx + ((<%= stopoff %> - <%= soff %>) * width)+1;
    var inst = "<%= crenau.instrument.name %>";
    var cred = "<%= 'crenaured' unless crenau.valide %>"
    var div='<a href="crenaus/<%= crenau.id %>/edit"><div class="divcrenau myflex2 myalign ' + cred + '" style="z-index:10; top: '+offtop+'px;left:'+min_start+'px;height:' + (height+1) + 'px;width:' + duree + 'px;background-color: #<%= @colors[crenau.instrument.id] %>;">'+inst+'</div></a>'
    <% if crenau.recurence != 3 %>
      document.body.querySelector("#<%= ids %>").insertAdjacentHTML( 'afterbegin',  div);
    <% end %>
  <% end %>
  window.onresize = function(event) {location.reload();}
</script>

app/views/crenaus/edit.html.erb
<div class="myflex content-title">
  <p><%= render 'shared/logo' %> /
    <%= link_to "Créneaux", adherent_crenaus_path(@adherent) %> / Modifier</p>

  <%= render 'shared/logout' %>
</div>
<div class="content-bandeau">
  <%= render 'form', crenau: @crenau %>
</div>

app/views/crenaus/index.html.erb
<div class="myflex content-title">
  <p><%= render 'shared/logo' %> / Créneaux</p>
  <%= render 'shared/logout' %>
</div>


<div class="content-table">
  <div class="hcont">
    <table id= "crenautable" class="table-crenau">
      <tr>
          <td class="hrefer"><div class="plabel"><%= link_to fa_icon('plus-circle'), new_adherent_crenau_path(@adherent), title: "Ajouter un créneau" %></div></td>
          <td></td>
        <% (8..21).each do |i| %>
          <td class="hrefer"><div class="hlabel"><%= i %>H</div></td>
          <td class=""></td>
          <td class=""></td>
          <td class="minfin"><div class="hlabelfin"><%= "22H" if i== 21 %></div></td>
        <% end %>
      </tr>
      <% (0..6).each do |j|
        jour = @jours[j] %>
        <tr>
          <td rowspan="2" class ="tjour"><%= @jours[j] %></td>
          <td class="rec">P</td>
          <% (8..21).each do |i| %>
            <td id='<%= "t#{j}_P_#{i}_0" %>' class="heureh"></td>
            <td id='<%= "t#{j}_P_#{i}_15" %>' class="minh"></td>
            <td id='<%= "t#{j}_P_#{i}_30" %>' class="minh"></td>
            <td id='<%= "t#{j}_P_#{i}_45" %>' class="minh <%= "cfin" if i== 21 %>"></td>
          <% end %>
            <td id='<%= "t#{j}_P_22_0" %>' style="visibility: hidden;" class="heureh"></td>
        </tr>
        <tr>
          <td class="rec">I</td>
          <% (8..21).each do |i| %>
            <td id='<%= "t#{j}_I_#{i}_0" %>' class="heure"></td>
            <td id='<%= "t#{j}_I_#{i}_15" %>' class="min"></td>
            <td id='<%= "t#{j}_I_#{i}_30" %>' class="min"></td>
            <td id='<%= "t#{j}_I_#{i}_45" %>' class="min <%= "cfin" if i== 21 %>"></td>
          <% end %>
            <td id='<%= "t#{j}_I_22_0" %>' style="visibility: hidden;" class="heure"></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>


<hr>
<div class="center"><u>Les créneaux ponctuels</u></div>
  <div class="content-table">
        <table class="striped responsive-table">
          <thead>
            <tr>
              <th>Prof</th>
              <th>Jour</th>
              <th>Recurence</th>
              <th>Instrument</th>
              <th>Discipline</th>
              <th>DE</th>
              <th>A</th>
              <th colspan="1"></th>
            </tr>
          </thead>

          <tbody>
            <% @crenaus.each do |crenau|
              if crenau.recurence == 3 %>
                <tr class="<%= crenau.valide %> pointer" onclick="location.href='<%= edit_adherent_crenau_path(@adherent, crenau) %>'">


                  <td><%= crenau.user.fullname %></td>

                  <td><%= @jours[crenau.jour] %></td>
                  <td><%= @recurences[crenau.recurence] %></td>
                  <td><%= crenau.instrument.name %></td>
                  <td><%= crenau.discipline.name %></td>
                  <td><%= crenau.start.strftime("%H:%M") %></td>
                  <td><%= crenau.end.strftime("%H:%M") %></td>
                  <td><%= link_to fa_icon("trash-o"), adherent_crenau_path(@adherent,crenau), method: :delete, data: { confirm: 'Supprimer le créneau?' } %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
</div>



<script type="text/javascript">
  // Mon code Javascript
  var vartop2 = document.body.querySelector("#t0_P_8_0").offsetLeft;
  var vartop3 = document.body.querySelector("#t0_P_21_45").offsetLeft;
  var width = ((vartop3-vartop2)/((14*4)-1)/15);

  <% @crenaus.each do |crenau|
    ms = (crenau.start.strftime("%M").to_i / 15).round * 15
    mhs = crenau.start.strftime("%H").to_i
    ids = "t#{crenau.jour}_P_" + mhs.to_s + "_"+ ms.to_s
    soff = crenau.start.strftime("%M").to_i - ms

    mstop = (crenau.end.strftime("%M").to_i / 15).round * 15
    mhstop = crenau.end.strftime("%H").to_i
    idstop = "t#{crenau.jour}_P_" + mhstop.to_s + "_"+ mstop.to_s
    stopoff = crenau.end.strftime("%M").to_i - mstop %>

    var height = document.body.querySelector("#t0_P_8_0").getBoundingClientRect().height;
    var x1 = document.body.querySelector("#<%= ids %>").offsetLeft;
    var x2 = document.body.querySelector("#<%= idstop %>").offsetLeft;
    var lenghtx = x2 - x1
    var offtop = -1

    <% case crenau.recurence %>
        <% when 0 %>
          height *= 2;
        <% when 1 %>
        <% when 2 %>
          offtop = height-1;
    <% end %>

    var min_start = Math.round(<%= soff %> * width)-1;
    var duree = lenghtx + ((<%= stopoff %> - <%= soff %>) * width)+1;
    var inst = "<%= crenau.instrument.name %>";
    var cred = "<%= 'crenaured' unless crenau.valide %>"
    var div='<a href="crenaus/<%= crenau.id %>"><div class="divcrenau myflex2 myalign ' + cred + '" style="z-index:10; top: '+offtop+'px;left:'+min_start+'px;height:' + (height+1) + 'px;width:' + duree + 'px;background-color: #<%= @colors[crenau.instrument.id] %>;">'+inst+'</div></a>'
    <% if crenau.recurence != 3 %>
      document.body.querySelector("#<%= ids %>").insertAdjacentHTML( 'afterbegin',  div);
    <% end %>
  <% end %>
  window.onresize = function(event) {location.reload();}
</script>

app/views/crenaus/new.html.erb
<div class="myflex content-title">
  <p><%= render 'shared/logo' %> /
    <%= link_to "Créneaux", adherent_crenaus_path(@adherent) %> / Nouveau</p>

  <%= render 'shared/logout' %>
</div>
<div class="content-bandeau">
  <%= render 'form', crenau: @crenau %>
</div>

app/views/crenaus/show.html.erb
<div class="myflex content-title">
  <p><%= render 'shared/logo' %> /
    <%= link_to "Créneaux", adherent_crenaus_path(@adherent) %> / Edition</p>

  <%= render 'shared/logout' %>
</div>
    <%=  render 'ajax' %>
<div class="tablestudent">
  <div class="center">
    Elèves inscrits sur ce crénau :
  </div>
  <% @cours.each do |cour|
    @cour = cour %>
        <%= render 'ajax' %>
  <% end %>
</div>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<script type="text/javascript">

 document.querySelector('#crenau_jour').addEventListener('change', function (ev) {
      var url = "/adherent/" + <%= current_user.id  %> + "/crenaus/" + <%= @crenau.id %> + "/edit";
      var url = "<%= adherent_crenau_ajax_path(current_user, @crenau) %>";
console.log(url);
    fetch(url)
      .then(function(response) {
        response.text().then(function(text) {
          document.querySelector('#mycrenau').innerHTML = text;

        });
      })
    });
</script>