config/routes.rb
Rails.application.routes.draw do


  resources :years, except: [:show]
  resources :instruments, except: [:show] do
    get 'ajax', to: "instruments#ajax"
    get 'ajaxd', to: "instruments#ajaxd"
  end
  resources :tarifs, except: [:show]
  resources :disciplines, except: [:show]

  resources :students do
    resources :cours
  end
  # resources :crenaus
  resources :adherent do
    resources :adhesions, only: [:new, :update]
    resources :students
    get 'query', to: 'students#query'
    get 'yes', to: 'students#yes'
    get 'querytwo', to: 'students#querytwo'
    get 'profile', to: "adherent#profile"
    resources :crenaus do
      get 'ajax', to: "crenaus#ajax"
    end
  end
  resources :users, only: [] do
    resources :crenaus, only: [:create, :show, :update, :destroy]
  end
devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do
    authenticated :user do
      root 'adherent#root', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
root 'pages#home'

get 'profs', to: 'adherent#profs'
get 'bureau', to: 'adherent#bureau'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/adherent_controller.rb
class AdherentController < ApplicationController
  before_action :set_adherent, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = "first_name ILIKE :query OR last_name ILIKE :query"
      @title = "Résultats"
      @adherents = User.where(sql_query, query: "%#{params[:query]}%").order('function_id, first_name')
    else
      @title = "Adhérents"
      @adherents = User.joins(:years).where(years: {name: @saison.name}).order('first_name DESC')
    end
    @link = "Adhérent"
    render "index"
  end

  def bureau
    @title = "Membre du bureau "
    @link = "Bureau"
    @adherents = User.joins(:function).where("functions.name = 'Président' OR functions.name = 'Trésorier' OR functions.name = 'Secrétaire' OR functions.name = 'Bureau'").order('function_id').reverse
    render "index"
  end

  def profs
    @title = "Professeurs"
    @link = "Professeur"
    @adherents = User.joins(:function).where(functions: {name: "Professeur"}).order('first_name')
    render "index"
  end

  # def crenaus
  #   @adherent = User.find(params[:adherent_id])
  #   @crenaus = Crenau.where(year: @saison).rewhere(user: @adherent).order(:valide, :jour)
  # end

  def new
    params['role'] ? @role = params['role'] : @role = "Adhérent"
    @adherent = User.new
    @adherent.function = Function.find_by(name: @role)
  end

  def create
    @adherent = User.new(adherent_params)
    if @adherent.save
      redirect_to adherent_query_path(@adherent), :notice => "Adhérent enregistré!"
    else
      render "new"
    end
  end

  def update
    myparams = adherent_params
    @adherent.first_name = myparams["first_name"]
    @adherent.last_name = myparams["last_name"]
    @adherent.address = myparams["address"]
    @adherent.address2 = myparams["address2"]
    @adherent.zipcode = myparams["zipcode"]
    @adherent.city = myparams["city"]
    @adherent.tel1 = myparams["tel1"]
    @adherent.tel2 = myparams["tel2"]
    @adherent.function_id = myparams["function_id"]
        if @adherent.save
                redirect_to adherent_path(@adherent), :notice => "Adhérent enregistré!"
        else
                render "edit"
        end
  end

  def show
    @crenaus = Crenau.where("year_id = '#{@saison.id}' AND user_id = '#{@adherent.id}'")
    @adhesion = Adhesion.find_by(user: current_user, year: @saison)
  end

  def root
    redirect_to adherent_path(current_user)
  end

  def profile

    @adherent = User.find(params[:adherent_id])
  end

  def edit
  end

  def destroy
    @adherent.destroy
    redirect_to adherent_index_path, notice: 'Adhérent effacé.'
  end

  private

  def set_adherent
    @adherent = User.find(params[:id])
  end

  def adherent_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :address, :address2, :zipcode, :city, :tel1, :tel2, :function_id)
  end
end

app/views/adherent/_form.html.erb
        <div class="myflex">
          <div class="twocol">
            <%= @f.input :first_name, label: 'Nom', required: true %>
          </div>
          <div class="twocol">
            <%= @f.input :last_name, label: 'Prénom', required: true %>
          </div>
        </div>
        <%= @f.input :address, label: 'Adresse', required: true  %>
        <%= @f.input :address2, label: 'Adresse 2' %>
        <div class="myflex">
          <div class="tiercol">
            <%= @f.input :zipcode, label: 'Code postal', required: true %>
          </div>
          <div class="restcol">
            <%= @f.input :city, label: 'Ville', placeholder: 'Ville', required: true %>
          </div>
        </div>
        <div class="myflex">
          <div class="twocol">
            <%= @f.input :tel1, label: 'Téléphone 1', required: true %>
          </div>
          <div class="twocol">
            <%= @f.input :tel2, label: 'Téléphone 2' %>
          </div>
        </div>

      <%= @f.collection_select(:function_id, Function.all.reverse, :id, :name, {:class=>'visible'}) if @auth %>

app/views/adherent/_profilecol.html.erb
          <ul>
            <% if @adherent.years.include?(@saison) %>
              <% @adherent.students.each do |student| %>
                <li class="collection-item"><%= link_to student.fullname, student_path(student), class: "fa fa-graduation-cap" %></li>
              <% end %>
              <li class="collection-item">
                <%= link_to new_adherent_student_path(@adherent) do  %>
                  <i class="fa fa-plus-circle" aria-hidden="true" title="Ajouter un élève"></i>Ajouter un élève
                <% end %>
              </li>
            <% end %>
          </ul>

app/views/adherent/_showadherent.html.erb
      <div class="row">
        <div class="col s4">
          <%= render 'profilecol' %>
        </div>
        <div class="col s4">

        </div>
        <div class="col s4">
          <ul>
          </ul>
        </div>
      </div>

app/views/adherent/_showadmin.html.erb
      <div class="row">
        <div class="col s12 m6 l3">
          <%= render 'profilecol' %>
        </div>

        <div class="col s12 m6 l3">
          <ul>
            <li class="collection-item"><%= link_to " Bureau", bureau_path, class: "fa fa-users" %></li>
            <li class="collection-item"><%= link_to " Professeurs", profs_path, class: "fa fa-user-secret" %></li>
            <li class="collection-item"><%= link_to " Adhérents", adherent_index_path, class: "fa fa-address-book" %></li>
            <li class="collection-item"><%= link_to " Elèves", students_path, class: "fa fa-graduation-cap" %></li>
          </ul>
        </div>
        <div class="col s12 m6 l3">
          <ul>
            <li class="collection-item"><%= link_to " Créneaux", adherent_crenaus_path(@adherent), class: "fa fa-calendar" %></li>
            <li class="collection-item"><%= link_to " Inscriptions", "#", class: "fa fa-info" %></li>
          </ul>
        </div>
        <div class="col s12 m6 l3">
          <ul>
            <li class="collection-item"><%= link_to " Instruments", instruments_path, class: "fa fa-music" %></li>
            <li class="collection-item"><%= link_to " Formules", disciplines_path, class: "fa fa-server" %></li>
            <li class="collection-item"><%= link_to " Tarifs", tarifs_path, class: "fa fa-bitcoin" %></li>
            <li class="collection-item"><%= link_to " Saisons", years_path, class: "fa fa-black-tie" %></li>
          </ul>
        </div>
      </div>

app/views/adherent/_showprof.html.erb
      <div class="row">
        <div class="col s4">
          <ul>
            <li class="collection-item"><%= link_to " Créneaux", adherent_crenaus_path(@adherent), class: "fa fa-calendar" %></li>
          </ul>
        </div>
        <div class="col s4">
          <ul>
        </div>
        <div class="col s4">
          <ul>
          </ul>
        </div>
      </div>

app/views/adherent/edit.html.erb
<div class="title">
  <h4><a href="#" onClick="history.go(-1);return true;">
      <i class="fa fa-chevron-circle-left"></i></a></h4>
  <h4>Edit adhérent</h4>
  <h4></h4>
</div>
<div class="mycard">
  <%= simple_form_for @adherent, :url => adherent_path, :method => :put do |f| %>
    <% @f=f %>
    <%= @f.error_notification %>

    <div class="form-inputs">
      <%= render 'form' %>
    </div>
    <div class="form-actions">
      <%= @f.button :submit, "Enregistrer" %>
    </div>

  <% end %>
</div>

app/views/adherent/index.html.erb
<div class="row back rowshadow ">
  <div class="content col s12">
    <div class="myflex content-title">
      <p><%= render 'shared/logo' %> / <%= @title %></p>
      <%= form_tag adherent_index_path, method: :get do %>
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Rechercher un membre" %>
      <% end %>
      <%= render 'shared/logout' %>

    </div>
    <div class="content-table">

      <table class="striped responsive-table">
        <thead>
          <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Fonction</th>
            <th class="right"><%= link_to fa_icon('plus-circle'), "#{new_adherent_path}?role=#{@link}", title: "Ajouter un #{@title[0...-1]}" if @auth %></th>
          </tr>
        </thead>
        <tbody>
          <% @adherents.each do |adherent| %>
            <tr class="<%= adherent.years.include?(@saison) %> pointer" onclick="location.href='<%= adherent_path(adherent) %>'">
              <td><%= adherent.first_name %></td>
              <td><%= adherent.last_name %></td>
              <td><%= adherent.function.name %></td>
              <td><%= link_to adherent_path(adherent), class: "secondary-content", method: :delete, data: { confirm: "Supprimer l'adherent?" } do %>
                <i class="fa fa-trash-o" aria-hidden="true" title="Supprimer"></i>
              <% end %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

app/views/adherent/new.html.erb
<div class="title">
  <h4><a href="#" onClick="history.go(-1);return true;">
        <i class="fa fa-chevron-circle-left"></i></a></h4>
  <h4>Nouveau membre</h4>
  <h5></h5>
</div>
<div class="mycard">
  <%= simple_form_for @adherent, :url => adherent_index_path, :method => :post do |f| %>
    <% @f=f %>
    <%= @f.error_notification %>
    <div class="form-inputs">
      <div class="row">
        <div class="col s4 separator padding">
          <%= @f.input :email, required: true, autofocus: true %>
          <%= @f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          <%= @f.input :password_confirmation, required: true %>
          <br/><br/>
          <div class="form-actions">
            <%= f.button :submit, "Enregistrer" %>
          </div>
        </div>
        <div class="col s8 padding">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/adherent/profile.html.erb
    <div class="myflex content-title">
      <p><%= render 'shared/logo' %> / Profil</p>
      <%= render 'shared/logout' %>
    </div>
    <div class="row">
      <div class="col s12 m6">
        <div class="content-form">
          <u><%= @adherent.function.name %></u>
          <p><%= @adherent.address %><br/>
            <% if @adherent.address2.length > 0 %>
              <%= @adherent.address2 %><br/>
            <% end %>
            <%= @adherent.zipcode %> <%= @adherent.city %><br/><br/>
            Email : <%= @adherent.email %><br/>
            Téléphone : <%= @adherent.tel1 %><br/>
            <% if @adherent.tel2 != "" %>
              Téléphone 2 : <%= @adherent.tel2 %>
            <% end %>
          </p>
          <%= link_to " Modifier", edit_adherent_path(current_user), class: "fa fa-pencil" %>
        </div>
      </div>
      <div class="col s12 m6">
        <div class="content-form">
          <% if @adherent.years.include?(@saison) %>
            Adhérent <%= @saison.name %></h1>
            <hr>
            <h1><u>Elèves :</u></h1>
            <p><% @students = @adherent.students %>
            <%= render 'shared/studentlist' %></p>
          <% else %>
            Non adhérent</h1>
            <%= link_to " Adhérer", new_adherent_adhesion_path(@adherent), class: "fa fa-plus-circle", data: { confirm: "Prendre l'adhésion #{@saison.name}?" } %>
          <% end %>

        </div>
      </div>
    </div>

app/views/adherent/rebut_profile.html.erb
    <div class="myflex content-title">
      <p><%= render 'shared/logo' %> / Profil</p>
      <%= render 'shared/logout' %>
    </div>
    <div class="row">
      <div class="col s12 m6">
        <div class="content-form">
          <u><%= @adherent.function.name %></u>
          <p><%= @adherent.address %><br/>
            <% if @adherent.address2.length > 0 %>
              <%= @adherent.address2 %><br/>
            <% end %>
            <%= @adherent.zipcode %> <%= @adherent.city %><br/><br/>
            Email : <%= @adherent.email %><br/>
            Téléphone : <%= @adherent.tel1 %><br/>
            <% if @adherent.tel2 != "" %>
              Téléphone 2 : <%= @adherent.tel2 %>
            <% end %>
          </p>
          <%= link_to " Modifier", edit_adherent_path(current_user), class: "fa fa-pencil" %>
        </div>
      </div>
      <div class="col s12 m6">
        <div class="content-form">
          <% if @adherent.years.include?(@saison) %>
            Adhérent <%= @saison.name %></h1>
            <hr>
            <h1><u>Elèves :</u></h1>
            <p><% @students = @adherent.students %>
            <%= render 'shared/studentlist' %></p>
          <% else %>
            Non adhérent</h1>
            <%= link_to " Adhérer", new_adherent_adhesion_path(@adherent), class: "fa fa-plus-circle", data: { confirm: "Prendre l'adhésion #{@saison.name}?" } %>
          <% end %>

        </div>
      </div>
    </div>

app/views/adherent/show.html.erb
<div class="myflex content-title">
  <p><%= render 'shared/logo' %> /</p>
  <%= render 'shared/logout' %>
</div>
<div class="row back rowshadow">
  <div class="col s3">
    <div class="content-form">
      <u><%= @adherent.function.name %></u>
      <p><%= @adherent.address %><br/>
        <% if @adherent.address2.length > 0 %>
          <%= @adherent.address2 %><br/>
        <% end %>
        <%= @adherent.zipcode %> <%= @adherent.city %><br/><br/>
        Email : <%= @adherent.email %><br/>
        Téléphone : <%= @adherent.tel1 %><br/>
        <% if @adherent.tel2 != "" %>
          Téléphone 2 : <%= @adherent.tel2 %>
        <% end %>
      </p>
      <%= link_to " Modifier", edit_adherent_path(current_user), class: "fa fa-pencil" %>
    </div>

    <div class="content-form">
      <% if @adherent.years.include?(@saison) %>
        Adhérent <%= @saison.name %></h1>
      <% else %>
        Non adhérent <%= @saison.name %></h1>
        <%= link_to " Adhérer", new_adherent_adhesion_path(@adherent), class: "fa fa-plus-circle", data: { confirm: "Prendre l'adhésion #{@saison.name}?" } %>
      <% end %>
    </div>

  </div>
  <div class="content col s9">
      <%= render 'showprof' if @adherent.function.name == "Professeur" %>
      <%= render 'showadmin' if ["Bureau", "Admin"].include?(@adherent.function.name) %>
      <%= render 'showadherent' if @adherent.function.name == "Adhérent" %>
  </div>
</div>